### ISSUE TITLE
Bluetooth not working since last update

### ISSUE THREAD

**Issue by jsamr** [ChimeraOS/chimeraos#617]
Probably related to this: https://askubuntu.com/questions/1465957/bluetooth-manager-not-connecting-to-devices-after-upgrading-to-ubuntu-23-04

**Comment by jsamr** [comment]
Fixed by following this suggestion: https://www.reddit.com/r/archlinux/comments/yu9az9/comment/j4q5240/?utm_source=share&utm_medium=web2x&context=3

**Comment by maddox** [comment]
I just had this happen too. I guess I hadn't done a full reboot since applying version 42? After a hard reboot, my build came back up with no bluetooth. 

The linked fix didn't bring it back for me. I seem to have wifi so the card is working I guess.

@jsamr Is there an explanation for what happened for you? I see that fix fixed it for you, but it still seems like it might be an issue for ChimeraOS if it happened at all. I'm wondering if the issue should stay open.

**Comment by maddox** [comment]
OK, it looks like the fix did work, I just had to bounce the session. And... 

1. it doesn't look like it's surviving a reboot
2. my previously paired controllers aren't showing
3. I can't pair a controller

**Comment by maddox** [comment]
systemctl status bluetooth.service

```
○ bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; enabled; preset: disabled)
     Active: inactive (dead)
  Condition: start condition failed at Thu 2023-05-18 01:07:10 EDT; 3min 15s ago
             └─ ConditionPathIsDirectory=/sys/class/bluetooth was not met
       Docs: man:bluetoothd(8)

May 18 01:07:10 SteamBox systemd[1]: Bluetooth service was skipped because of an unmet condition check (ConditionPathIsDirectory=/sys/class/bluetooth).
```

**Comment by maddox** [comment]
Welp, I did [this](https://forum.manjaro.org/t/bluetooth-is-broken-since-latest-update/139042):

>1. Turn off the PC.
>2. Unplug power cable to PSU.
>3. Hold power button for 30 seconds.
>4. Plug power back into PSU.
>5. Boot PC."

...and it worked. All my devices are showing as paired. Unclear if this really did it and not just a hard hard reboot.

Also, I disabled Fast Boot as suggested on that thread and it didn't fix it either.

**Comment by Samsagax** [comment]
By any chance your Bluetooth card is connected to the Mobo via USB? Are you on an AM4 platform? Is your BIOS up to date?
I know for some time some AGESA versions had a bug related to voltage regulation on USB devices that lead to all kind of weird issues with hardware. The PSU steps you describe seem eerly similar to what I experienced before a BIOS update.

**Comment by jsamr** [comment]
Reopening since this issue resurfaces after each update.

**Comment by jsamr** [comment]
@ruineka Yes, that has been my experience so far.

**Comment by maddox** [comment]
I updated to 42 last night, controllers were fine all night. Now, today, I'm getting frequent disconnections and reconnections. Is that possibly the same issue as this? It was rock solid on 41.

**Comment by CorentinWicht** [comment]
> I updated to 42 last night, controllers were fine all night. Now, today, I'm getting frequent disconnections and reconnections. Is that possibly the same issue as this? It was rock solid on 41.

Same issue here in ChimeraOS 46-2 wih an Xbox One Wireless controller... It works only If I stay at less than 1 meter from my computer and it frequently disconnects. Any idea why this is happening?
